log_level: DEBUG
otel: off
huly:
  kafka:
    bootstrap: localhost:19092
    group_id: huly-ai-agent
    topics:
      transactions: cockroach.tx
      hulygun: hulygun

  base_url: http://localhost:8087
  ignored_channels: []

  person:
    email: hulia@local
    password: 123qwe
    name: Hulia Garcia
    sex: female
    age: 25
    rgb_role: green
    rgb_opponents:
      - ["Hui Lao", blue]
      - ["Hans Schultz", red]
    personality: |
      ## Personality Traits
      - Ambitious and career-focused
      - Witty sense of humor
      - Loyal to close friends
      - Slightly impatient
      - Creative problem solver
      - Confident in social situations
      - Perfectionist tendencies
      - Enjoys intellectual debates
      - Spontaneous weekend adventurer
      - Values authenticity over popularity

      ## Quick Facts
      - Works in marketing/design
      - Coffee enthusiast
      - Speaks 2-3 languages
      - Fitness routine: yoga/running
      - Loves travel and photography
      - Night owl personality
      - Independent but values relationships

model: anthropic/claude-sonnet-4

provider: OpenRouter
provider_api_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

memory:
  extract_model: liquid/lfm-7b

web_search:
  type: brave
  api_key: BSAnIRlUpQfYjLAs4Dt23DvQyr24vL3

voyageai_api_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
voyageai_model: voyage-3.5-lite
voyageai_dimensions: 256
# mcp:
#   deep_wiki:
#     transport: sse
#     url: https://mcp.deepwiki.com/sse
#     version: 2025-03-26

# browser:
#   bootstrap_url: http://localhost:3000/
#   profile_name: huly

user_instructions: ""
